// 기능 권한 코드 — 백엔드 com.erp.common.security.Permission 과 일치해야 한다.
export const PERM = {
  HR_EMPLOYEE_READ: 'hr:employee:read',
  HR_EMPLOYEE_WRITE: 'hr:employee:write',
  HR_DEPARTMENT_READ: 'hr:department:read',
  HR_DEPARTMENT_WRITE: 'hr:department:write',
  HR_LEAVE_READ: 'hr:leave:read',
  HR_LEAVE_WRITE: 'hr:leave:write',
  HR_POSITION_READ: 'hr:position:read',
  HR_POSITION_WRITE: 'hr:position:write',
  HR_JOBGRADE_READ: 'hr:jobgrade:read',
  HR_JOBGRADE_WRITE: 'hr:jobgrade:write',
  FINANCE_READ: 'finance:read',
  FINANCE_WRITE: 'finance:write',
  FINANCE_INVOICE_APPROVE: 'finance:invoice:approve',
  FINANCE_INVOICE_PAY: 'finance:invoice:pay',
  FINANCE_GL_APPROVE: 'finance:gl:approve',
  FINANCE_SETTING_WRITE: 'finance:setting:write',
  INVENTORY_READ: 'inventory:read',
  INVENTORY_WRITE: 'inventory:write',
  INVENTORY_MOVEMENT_APPROVE: 'inventory:movement:approve',
  CRM_READ: 'crm:read',
  CRM_WRITE: 'crm:write',
  AUDIT_READ: 'audit:read',
  IAM_READ: 'iam:read',
  IAM_WRITE: 'iam:write',
} as const
